jenkins:
  systemMessage: "🚀 Configured by Ansible + JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "{{ jenkins_admin_user }}"
          password: "{{ jenkins_admin_password }}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

